# Generated by Django 5.1.4 on 2024-12-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='license_number',
        ),
    ]
