# Generated by Django 5.1.3 on 2024-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='CPR_number',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
