# Generated by Django 5.1.3 on 2024-12-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplan',
            name='date_of_issue',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user__role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
