# Generated by Django 5.1.3 on 2024-12-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_careplan_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
