# Generated by Django 5.1.4 on 2024-12-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employee_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='available_days',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], max_length=15),
        ),
    ]
