# Generated by Django 5.1.3 on 2024-12-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_chronic_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
