# Generated by Django 5.1.4 on 2024-12-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_prescription_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
